version: '3.7'
services:
  # Client
  frontend:
    image: node:12.22.1-alpine    
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - '3004:3000'
    volumes:
      - '.:/var/www'
      - /var/www/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true yarn start
    command: /var/www/boot.sh
