version: '3.7'
services:
  frontend:
    image: node:12.22.1-alpine    
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - '3004:3000'
    volumes:
      - '.:/var/www'
      - /var/www/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true yarn start
    command: /var/www/deploy.sh
    networks:
      - shared

  webserver:
    image: nginx:1.17.10-alpine
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - '80:80'
    volumes:
      - '.:/var/www'
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - shared

#Docker Networks
networks:
  shared:
    driver: bridge